import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "PokeAPI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link
  rel="icon"
  href="/favicon-32x32.png"
  type="image/png"
  sizes="32x32"
/></head>
      <body
        className={`font-[Bubblegum] antialiased bg-[url("/pokeBG.jpg")] bg-cover bg-no-repeat bg-center`}
      >
        {children}
      </body>
    </html>
  );
}

// ${bubblegumSans.variable} ${geistMono.variable}