import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bubblegum_Sans } from "next/font/google";
import "./globals.css";

 export const bubblegumSans = Bubblegum_Sans({
  variable: "--font-bubblegum-sans",
  subsets: ["latin"],
  weight: "400"
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PokeAPI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bubblegumSans.variable} antialiased bg-[url("/pokeBG.jpg")] bg-cover bg-no-repeat bg-center`}
      >
        {children}
      </body>
    </html>
  );
}

// ${bubblegumSans.variable} ${geistMono.variable}